### ISSUE TITLE
AssertionError [ERR_ASSERTION]: false == true

### ISSUE THREAD

**Issue by misterfresh** [spdy-http2/spdy-transport#47] opened 2017-06-25 22:08 UTC
I get the error  
assert.js:60
  throw new errors.AssertionError({
at PriorityNode.removeChild (node_modules\spdy-transport\lib\spdy-transport\priority.js:74:3)
at PriorityNode.remove ( node_modules\spdy-transport\lib\spdy-transport\priority.js:62:15)
    at PriorityTree.add ( node_modules\spdy-transport\lib\spdy-transport\priority.js:163:23)
    at Stream._initPriority ( node_modules\spdy-transport\lib\spdy-transport\stream.js:101:25)
    at new Stream ( node_modules\spdy-transport\lib\spdy-transport\stream.js:76:8)
    at Connection._createStream ( node_modules\spdy-transport\lib\spdy-transport\connection.js:388:16)
    at Connection._handleHeaders ( node_modules\spdy-transport\lib\spdy-transport\connection.js:436:21)
    at Connection._handleFrame ( node_modules\spdy-transport\lib\spdy-transport\connection.js:319:10)
    at Parser.<anonymous> ( node_modules\spdy-transport\lib\spdy-transport\connection.js:156:10)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk ( node_modules\readable-stream\lib\_stream_readable.js:283:12)
    at readableAddChunk ( node_modules\readable-stream\lib\_stream_readable.js:270:11)
    at Parser.Readable.push ( node_modules\readable-stream\lib\_stream_readable.js:237:10)
    at Parser.Transform.push ( node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at next ( node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:53:12)

This happens on http2 push from server

**Comment by misterfresh** [comment] 2017-06-25 22:17
I commented the line 74 "assert(index !== -1)" in spdy-transport\lib\spdy-transport\priority.js:74:3
and now the server is not crashing any more...

To give context, I am pushing a lot of files with http2 push, and for every file that is not actually requested by the client, I get the error 
link /js/vendors/aphrodite push error Error: Got RST: REFUSED_STREAM
    at Stream._handleRST ( node_modules\spdy-transport\lib\spdy-transport\stream.js:281:24)
    at Stream._handleFrame ( node_modules\spdy-transport\lib\spdy-transport\stream.js:126:10)
    at Connection._handleFrame ( node_modules\spdy-transport\lib\spdy-transport\connection.js:324:12)
    at Parser.<anonymous> ( node_modules\spdy-transport\lib\spdy-transport\connection.js:156:10)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk ( node_modules\readable-stream\lib\_stream_readable.js:283:12)
    at readableAddChunk ( node_modules\readable-stream\lib\_stream_readable.js:270:11)
    at Parser.Readable.push ( node_modules\readable-stream\lib\_stream_readable.js:237:10)
    at Parser.Transform.push ( node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at next ( node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:53:12)
    at  node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:72:5
    at Parser.onRSTFrame (node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:368:3)
    at Parser.onFrameBody ( node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:144:10)
    at Parser.execute ( node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:64:8)
    at Parser._consume ( node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:95:8)

**Comment by matthewp** [comment] 2017-06-26 18:05
I submitted https://github.com/spdy-http2/spdy-transport/pull/48 which should fix your issue here.

**Comment by misterfresh** [comment] 2017-06-27 21:33
With your fix, I'm getting a slightly different error, but the server still crashes when a resource pushed by http2 server push is not requested by the client.

assert.js:60
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild ( node_modules\spdy-transport\lib\spdy-transport\priority.js:74:3)
    at PriorityNode.remove ( node_modules\spdy-transport\lib\spdy-transport\priority.js:62:15)
    at Stream._handlePriority ( node_modules\spdy-transport\lib\spdy-transport\stream.js:305:18)
    at Stream._handleFrame ( node_modules\spdy-transport\lib\spdy-transport\stream.js:128:10)
    at Connection._handleFrame ( node_modules\spdy-transport\lib\spdy-transport\connection.js:324:12)
    at Parser.<anonymous> ( node_modules\spdy-transport\lib\spdy-transport\connection.js:156:10)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk ( node_modules\readable-stream\lib\_stream_readable.js:283:12)
    at readableAddChunk ( node_modules\readable-stream\lib\_stream_readable.js:270:11)
    at Parser.Readable.push ( node_modules\readable-stream\lib\_stream_readable.js:237:10)
    at Parser.Transform.push ( node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at next ( node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:53:12)
    at  node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:72:5
    at Parser.onPriorityFrame ( node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:539:3)
    at Parser.onFrameBody ( node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:154:10)

**Comment by Aedaeum** [comment] 2018-02-27 19:39
Is there a workaround for this?
I just loaded up my webapp in firefox and got this error. For some reason I do not get this error when opening in Chrome.

**Comment by misterfresh** [comment] 2018-02-27 20:46
Here's a temporary fix : in your project's main package.json add:
```
"scripts": {
    "postinstall": "node ./conf/quickfix.js"
}
```
and in the quickfix.js file : 
```
let fs = require('fs')
let path = require('path')
let file = path.join(
    process.cwd(),
    'node_modules/spdy-transport/lib/spdy-transport/priority.js'
)

let data = fs
    .readFileSync(file)
    .toString()
    .split('\n')
if (data.length < 190) {
    data.splice(73, 0, '/*')
    data.splice(75, 0, '*/')
    data.splice(
        187,
        0,
        `
	var index = utils.binarySearch(this.list, node, compareChildren);
 	this.list.splice(index, 1);
`
    )
    let text = data.join('\n')

    fs.writeFile(file, text, function(err) {
        if (err) return console.log(err)
    })
}
```
now everytime you install spdy it will be patched if needed.

also node-http2 native is available, just not yet compatible with express

**Comment by Aedaeum** [comment] 2018-02-27 20:48
Thanks for this.
Do you know when the native will be compatible with express?

**Comment by misterfresh** [comment] 2018-02-27 21:33
no... there is an issue on it but I dont think they have a date yet

**Comment by th3nate** [comment] 2018-04-18 10:17
hello, 
im experiencing the same issue, 
although using **node-spdy** im getting the same error about the transport module with version 2.0.18
was this issue fixed in the newest version? 

AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild (/app/node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
    at PriorityNode.remove (/app/node_modules/spdy-transport/lib/spdy-transport/priority.js:62:15)
    at Stream._handlePriority (/app/node_modules/spdy-transport/lib/spdy-transport/stream.js:305:18)
    at Stream._handleFrame (/app/node_modules/spdy-transport/lib/spdy-transport/stream.js:128:10)
    at Connection._handleFrame (/app/node_modules/spdy-transport/lib/spdy-transport/connection.js:324:12)
    at Parser.<anonymous> (/app/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Parser.Readable.push (/app/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at Parser.Transform.push (/app/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at next (/app/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:53:12)
    at /app/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:72:5

**Comment by wmertens** [comment] 2018-05-24 11:59
How about just replacing the `assert(index !== -1)` with `if (index === -1) return`? Seems unsafe to let the function remove the last child from the list…

**Comment by vytautas-pranskunas-** [comment] 2018-07-18 14:58
Any progress on this one?

**Comment by mrbinky3000** [comment] 2018-09-06 19:38
I suddenly started experiencing this issue on webpack-dev-server.


```
AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
    at PriorityNode.remove (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/priority.js:62:15)
    at PriorityTree.add (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/priority.js:163:23)
    at Stream._initPriority (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/stream.js:101:25)
    at new Stream (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/stream.js:76:8)
    at Connection._createStream (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/connection.js:388:16)
    at Connection._handleHeaders (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/connection.js:436:21)
    at Connection._handleFrame (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/connection.js:319:10)
    at Parser.<anonymous> (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (/Users/me/myproject/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/me/myproject/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Parser.Readable.push (/Users/me/myproject/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at Parser.Transform.push (/Users/me/myproject/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at next (/Users/me/myproject/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:53:12)
```

**Comment by jordibartolome** [comment] 2018-09-07 14:58
Same problem here when updating to Chrome 69

**Comment by jordibartolome** [comment] 2018-09-07 15:15
The solution that misterfresh put on Feb 27th seems to fix it!

**Comment by antony-chopin** [comment] 2018-09-10 08:40
Due to this issue WDS is falling every 10-20 minutes. Madness.

**Comment by eyz** [comment] 2018-09-10 18:17
I only started seeing this after upgrading to Chrome 69 as well; same NPMs, same NodeJS version as before it was happening

**Comment by rathpc** [comment] 2018-09-11 14:17
I also experienced this issue with the following config:

Operating System: macOS Sierra (10.12.6)
Node Version: 8.11.2
NPM Version: 6.1.0
webpack Version: 2.7.0
webpack-dev-server Version: 2.11.2

I am using the patch fix mentioned by @misterfresh with some additional logic until an official fix is released.

**Comment by wmertens** [comment] 2018-09-11 15:51
is there anybody maintaining a forked npm package with the fix applied?

**Comment by eyz** [comment] 2018-09-12 00:29
The https://github.com/spdy-http2/spdy-transport/issues/47#issuecomment-369020176 fix is working well for me; no crashes from Chrome 69 clients after applying that. It would be nice to see this reviewed by the spdy-http2 folks and given priority as soon as possible. Does anyone have this fix as a PR to this project already?

@misterfresh have you submitted this fix already as a PR to this project? Is there anything blocking you doing so?

**Comment by johntran** [comment] 2018-09-13 01:01
@diasdavid is looking for maintainers for this repo and the org in general: https://github.com/spdy-http2/node-spdy/issues/339

**Comment by eyz** [comment] 2018-09-13 01:03
Sorry to be slightly off-topic, but I just got this stack trace today, and thus I am no longer using node-spdy

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Stream write aborted
    at /opt/cde/node_modules/spdy-transport/lib/spdy-transport/stream.js:141:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at Stream.onStreamError (/opt/cde/node_modules/spdy/lib/spdy/handle.js:110:18)
    at Stream.emit (events.js:182:13)
    at Stream.EventEmitter.emit (domain.js:442:20)
    at onwriteError (/opt/cde/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/opt/cde/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/opt/cde/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at /opt/cde/node_modules/spdy-transport/lib/spdy-transport/stream.js:239:23
    at /opt/cde/node_modules/spdy-transport/lib/spdy-transport/stream.js:141:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by mrG0bliN** [comment] 2018-09-21 11:39
* **v10.11.0**:
* **MSYS_NT-10.0 macOS 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys (it`s WINDOWS x64)**:
* **Subsystem**:



```
[04:04:30] AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(index !== -1)

    at PriorityNode.removeChild (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\priority.js:74:3)
    at PriorityNode.remove (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\priority.js:62:15)
    at PriorityTree.add (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\priority.js:163:23)
    at Stream._initPriority (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\stream.js:101:25)
    at new Stream (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\stream.js:76:8)
    at Connection._createStream (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\connection.js:388:16)
    at Connection._handleHeaders (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\connection.js:436:21)
    at Connection._handleFrame (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\connection.js:319:10)
    at Parser.<anonymous> (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\connection.js:156:10)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:460:23)
    at addChunk (D:\FRONTEND\www\company-m4leads-com\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (D:\FRONTEND\www\company-m4leads-com\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (D:\FRONTEND\www\company-m4leads-com\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (D:\FRONTEND\www\company-m4leads-com\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at next (D:\FRONTEND\www\company-m4leads-com\node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:53:12)
```
hello, i coding new site, after update or update same modules, i not understand, my watch started to break and throw an error.
a week ago this was not, I use for http2 spdy, gulp, webpack.
If you need any further information I can provide.

What causes the error? After every 10-15 minutes coding site there is such a bug, without a clue how this happens.

**Comment by pcnate** [comment] 2018-10-02 14:39
Same issue on Debian Linux. Same version of spdy-http2. I am using socket.io/socket.io-client with redbird proxy.

**Comment by ivnmaksimovic** [comment] 2018-10-04 09:30
Do not use Chrome Canary or new Chrome. I downgraded to Chrome 67 and I can develop without the watcher breaking all the time.

**Comment by jordibartolome** [comment] 2018-10-04 11:27
> Do not use Chrome Canary or new Chrome. I downgraded to Chrome 67 and I can develop without the watcher breaking all the time.

This is probably the worst reply I've read in time 😂

**Comment by ivnmaksimovic** [comment] 2018-10-04 11:42
@jordibartolome I am just referring to those having issue with webpack watch, that constantly breaks with "assert(index !== -1)" in spdy-transport\lib\spdy-transport\priority.js:74:3". I am not trying to contribute in fixing this issue. It's just a workaround for me, to be able to keep working on a project without having to rebuild every few minutes. It might help someone.

**Comment by nihlton** [comment] 2018-10-08 18:31
i've got the work around working - and thats great.

any word on this being fixed properly?

**Comment by pcnate** [comment] 2018-10-09 13:38
@nihlton #57 looks to fix the issue. Hopefully someone can get this confirmed and merged soon

**Comment by markmakes** [comment] 2018-10-12 17:02
Could this also potentially affect pre-flight OPTIONS requests?

Getting this on a client's site when attempting an API call to Azure: 
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

**Comment by intafon** [comment] 2018-10-15 20:13
Also using Chrome 69 -- ran @misterfresh 's patch, but still keeps crashing. . . anyone have any luck with any other ~~fix~~ patch?

**Comment by preeti-tm** [comment] 2018-10-23 08:47
I got the same error.

![image](https://user-images.githubusercontent.com/21260751/47348059-3e33f680-d6ce-11e8-92de-dd9439bb43d4.png)

**Comment by niftylettuce** [comment] 2018-10-24 04:03
my solution was to just upgrade to v8.8.1+, v8.x LTS, I did create https://github.com/niftylettuce/spdy-or-http2 this package as a fallback for whatever reason

**Comment by Grantlyk** [comment] 2018-11-02 12:01
Hey i've now started getting this error randomly today in my project, has anyone merged in a PR or got a release that fixes this issue?

**Comment by jacobheun** [comment] 2018-11-08 11:03
New versions of spdy (4.0.0) and spdy-transport (3.0.0) include this fix.

**Closed by jacobheun** 2018-11-08 11:03 UTC

**Comment by odinho** [comment] 2018-11-08 12:19
Awesome, opened a pull request for `webpack-dev-server`: https://github.com/webpack/webpack-dev-server/pull/1563

**Comment by benlind** [comment] 2018-11-30 18:20
If you are using `yarn` and want this fix for `webpack-dev-server`, add this to your `package.json`:

```
"resolutions": {
  "webpack-dev-server/**/spdy-transport": "^3.0.0"
}
```

Then run `yarn`.
